<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<OutputPath>..\..\build\</OutputPath>
	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.10" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nebula.Core.ImageTranslation\Nebula.Core.ImageTranslation.csproj" />
    <ProjectReference Include="..\Nebula.Core.CTF25.CCN\Nebula.Core.CTF25.CCN.csproj" />
    <ProjectReference Include="..\Nebula.Core.CTF25.MFA\Nebula.Core.CTF25.MFA.csproj" />
    <ProjectReference Include="..\Nebula.Core\Nebula.Core.csproj" />
  </ItemGroup>

</Project>
